---
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports: [3306:3306]
    healthcheck:
      test: [CMD, mysqladmin, ping, --silent]
      interval: 10s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports: [5672:5672, 15672:15672]
    environment:
      RABBITMQ_DEFAULT_USER: appuser
      RABBITMQ_DEFAULT_PASS: appuserpassword
    volumes: [./init-rabbitmq.sh:/docker-entrypoint-initdb.d/init-rabbitmq.sh]
  migrate:
    image: migrate/migrate
    depends_on:
      mysql:
        condition: service_healthy
    volumes: [./internal/infra/database/migrations:/migrations]
    entrypoint:
      - migrate
      - -path
      - /migrations
      - -database
      - mysql://root:root@tcp(mysql:3306)/orders
      - -verbose
      - up
  app:
    depends_on:
      rabbitmq:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    build: .
    image: cleanarch-app
    ports: [8000:8000, 50051:50051, 8080:8080]
    env_file: [./cmd/ordersystem/.env]
    command: [./main]
